"""Player identity resolution via a curated + generated alias map.

Source name formats disagree on multi-word/particle surnames:
  Kalshi / Odds API : "Alex de Minaur"  (First Last)  -> heuristic key "minaur_a"
  tennis-data       : "De Minaur A."     (Last I.)    -> heuristic key "de-minaur_a"

DEUCE's rating book is keyed by the tennis-data form, so the alias map unifies the
*truncated* First-Last key onto that full-surname canonical id. Result: all three
sources join exactly instead of via a hopeful string collapse.

Two files, both loaded once at import (hand-curated wins on conflict):
  - player_aliases.toml            (hand-curated overrides)
  - player_aliases_generated.toml  (machine-built from Sackmann; `deuce build-aliases`)
"""
from __future__ import annotations

import tomllib
from collections.abc import Callable, Iterable
from pathlib import Path

_DIR = Path(__file__).parent
_SEED = _DIR / "player_aliases.toml"
_GENERATED = _DIR / "player_aliases_generated.toml"


def _load_one(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    rev: dict[str, str] = {}
    for canonical_id, entry in data.get("player", {}).items():
        for key in entry.get("keys", []):
            rev[key] = canonical_id
    return rev


def _load_reverse_map() -> dict[str, str]:
    rev = _load_one(_GENERATED)   # machine-generated base
    rev.update(_load_one(_SEED))  # hand-curated overrides win
    return rev


_REVERSE: dict[str, str] = _load_reverse_map()


def apply_alias(heuristic_key: str) -> str:
    """Map a heuristic key onto its canonical player id (identity if no alias)."""
    return _REVERSE.get(heuristic_key, heuristic_key)


def alias_count() -> int:
    return len(_REVERSE)


def reload_aliases() -> None:
    global _REVERSE
    _REVERSE = _load_reverse_map()


# --------------------------------------------------------------------------- #
# Generation from Sackmann's authoritative first/last names                   #
# --------------------------------------------------------------------------- #
def build_aliases_from_sackmann(
    players: Iterable[tuple[str, str, str]],
    heuristic_key: Callable[[str], str],
) -> dict[str, dict]:
    """players: (player_id, name_first, name_last). `heuristic_key` is names._heuristic_key.

    For every player whose two name forms produce DIFFERENT keys (i.e. multi-token
    surnames), emit an alias mapping the First-Last truncation onto the Last-I.
    canonical id. Truncated keys claimed by more than one player are dropped as
    ambiguous (better a NaN than a wrong match)."""
    staged: dict[str, dict] = {}
    owners: dict[str, set[str]] = {}
    for pid, first, last in players:
        first, last = (first or "").strip(), (last or "").strip()
        if not first or not last:
            continue
        canonical = heuristic_key(f"{last} {first[0]}.")  # tennis-data form
        truncated = heuristic_key(f"{first} {last}")       # First-Last form
        if canonical == truncated:
            continue
        owners.setdefault(truncated, set()).add(canonical)
        e = staged.setdefault(canonical, {"display": f"{first} {last}", "keys": set(), "sackmann_id": str(pid)})
        e["keys"].add(truncated)
    out: dict[str, dict] = {}
    for canonical, e in staged.items():
        keys = sorted(k for k in e["keys"] if len(owners.get(k, ())) == 1)
        if keys:
            out[canonical] = {"display": e["display"], "sackmann_id": e["sackmann_id"], "keys": keys}
    return out


def dump_aliases_toml(aliases: dict[str, dict]) -> str:
    lines = [
        "# Machine-generated by `deuce build-aliases` from Sackmann player names.",
        "# Do NOT edit by hand — put hand-curated overrides in player_aliases.toml.",
        "",
    ]
    for cid in sorted(aliases):
        e = aliases[cid]
        keys = ", ".join(f'"{k}"' for k in e["keys"])
        lines += [
            f'[player."{cid}"]',
            f'display = "{e["display"]}"',
            f'sackmann_id = "{e["sackmann_id"]}"',
            f"keys = [{keys}]",
            "",
        ]
    return "\n".join(lines)


def write_generated(aliases: dict[str, dict]) -> Path:
    _GENERATED.write_text(dump_aliases_toml(aliases), encoding="utf-8")
    reload_aliases()
    return _GENERATED
