#!/usr/bin/env bash
# gen-state.sh — emit STATE.md (the model inventory) from the system.
#
# STATE.md is GENERATED, never hand-edited. This script is its only author.
# It composes three sources:
#   1. tools/state-inputs.tsv  — static facts the system cannot self-report
#      (risk tier = a review judgment; declared/design-intended stage).
#   2. the ledger (Postgres)   — effective stage, last-validated date, and
#      GO/NO-GO per scope from `validation_runs`. Used only if DATABASE_URL is
#      set and psql is available; otherwise those columns degrade to "n/a (no db)".
#   3. GAPS.md                 — open issues, matched to modules by known_issue_refs.
#
# Usage:  tools/gen-state.sh [output_path]      (default: STATE.md at repo root)
# Determinism note: STATE.md is a point-in-time report; the generated-at stamp is
# wall-clock by design and is NOT a decision-path time read (see STANDARDS S3).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INPUTS="$ROOT/tools/state-inputs.tsv"
GAPS="$ROOT/GAPS.md"
OUT="${1:-$ROOT/STATE.md}"
STAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
GITREV="$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)"

# --- DB availability ---------------------------------------------------------
DB_OK=0
if [ -n "${DATABASE_URL:-}" ] && command -v psql >/dev/null 2>&1; then
  if psql "$DATABASE_URL" -tAc 'SELECT 1' >/dev/null 2>&1; then DB_OK=1; fi
fi

# latest validation_runs.computed_at + GO/NO-GO for a scope; echoes "date|verdict"
db_latest() {
  local scope="$1"
  [ "$DB_OK" = 1 ] || { echo "n/a (no db)|n/a"; return; }
  psql "$DATABASE_URL" -tAc \
    "SELECT to_char(max(computed_at),'YYYY-MM-DD'), 'see-row' FROM validation_runs WHERE scope='${scope//\'/}'" \
    2>/dev/null | awk -F'|' 'NR==1{d=$1?$1:"none"; print d"|"($1?"recorded":"none")}' \
    || echo "query-failed|n/a"
}

# open GAPS count + whether a ref token appears in GAPS.md
gaps_open_count() { grep -cE '^\s*##+ ' "$GAPS" 2>/dev/null || echo 0; }
gaps_has_ref() { local ref="$1"; [ "$ref" = "-" ] && { echo ""; return; }
  grep -qiF "${ref//-/ }" "$GAPS" 2>/dev/null && echo "yes" || echo ""; }

# --- emit --------------------------------------------------------------------
{
  echo "# FORTUNA STATE (generated)"
  echo
  echo "> Purpose: what is actually running right now."
  echo "> Holds: the model inventory, one row per module, with ramp stage, risk tier, last-validated date, open gates, and known issues."
  echo "> Excludes: anything stable. Generated by tools/gen-state.sh; DO NOT hand-edit. Stable facts live in ARCHITECTURE.md, CONSTITUTION.md, NORTH_STAR.md, STANDARDS.md."
  echo
  echo "Generated: ${STAMP} at ${GITREV}. DB: $([ "$DB_OK" = 1 ] && echo 'connected' || echo 'not connected (effective-stage/last-validated columns degraded)')."
  echo
  echo "## Model and strategy inventory"
  echo
  echo "| Module | Kind | Risk tier | Declared stage | Last validated | GO surface | Known issues |"
  echo "|---|---|---|---|---|---|---|"
  while IFS=$'\t' read -r module kind tier dstage refs; do
    case "$module" in ''|'#'*) continue;; esac
    IFS='|' read -r lastval verdict <<<"$(db_latest "$module")"
    # Curated refs always surface; append a GAPS pointer when the ledger mentions it.
    issue="-"
    if [ "$refs" != "-" ]; then
      if [ -n "$(gaps_has_ref "$refs")" ]; then issue="$refs (in GAPS.md)"; else issue="$refs"; fi
    fi
    printf '| %s | %s | %s | %s | %s | %s | %s |\n' \
      "$module" "$kind" "$tier" "$dstage" "$lastval" "$verdict" "$issue"
  done < "$INPUTS"
  echo
  echo "## Open issues"
  echo
  echo "GAPS.md open sections: $(gaps_open_count). See [GAPS.md](GAPS.md) for the authoritative open-issue ledger; this generator does not duplicate their text."
  echo
  echo "Risk-tier legend: T1 critical (money/safety), T2 high, T3 medium, T4 low. Declared stage is design-intent; effective stage and last-validated come from the ledger when a DB is connected."
} > "$OUT"

echo "wrote $OUT (db=$([ "$DB_OK" = 1 ] && echo yes || echo no))"
